version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test0103Project
  gitServerName: githubProject
  gitUrl: https://github.com/rlakshitha0912/Test0103Project
  gitUsername: rlakshitha0912
  gitBranch: main
